### ISSUE TITLE
Add new shapes

### ISSUE THREAD

**Issue by MoOx** [MoOx/compass-recipes#16]
@chriscoyier added some shapes here http://css-tricks.com/examples/ShapesOfCSS/

**Comment by MoOx** [comment]
9ef2a211a29ee89a99ff9c91095d2e674d05108c

**Comment by MoOx** [comment]
There is moooooore http://cssdeck.com/labs/css-shapes/1

**Comment by MoOx** [comment]
``` css
.Crescent-moon-with-pure-CSS {
border-radius: 50%;
box-shadow: 10px 10px 0 #000;
height: 50px;
width: 50px;
}
```

https://twitter.com/_joshnh/statuses/237171669058334720
