### ISSUE TITLE
Reponsives images avoiding max-width & reflow

### ISSUE THREAD

**Issue by MoOx** [MoOx/compass-recipes#93]
Sassify this & make it a recipe

``` css
.embed-container {
    position: relative;    
    height: 0;
    overflow: hidden;
    background-color:black;   
}

.ratio-16-9{
    padding-bottom:56.25%; /* 9/16*100 */
}

.ratio-4-3{
    padding-bottom:75%; /* 3/4*100 */
}

.ratio-1-1{
    padding-bottom:100%; /* ... */  
}

.embed-container img{
    position: absolute;
    top: 0;
    left: 0;
    width:100%;
}
```

From here http://andmag.se/2012/10/responsive-images-how-to-prevent-reflow/
